[book]
authors = ["Michael Aldridge"]
language = "en"
multilingual = false
src = "src"
title = "SneakyNet Technical Overview"

[preprocessor.d2-go]
layout = "elk"
theme_id = 0

[output.html]
additional-css = ["custom.css"]
